name: qr_list
description: A list for shopping with QR-Codes.

version: 1.0.0+1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^0.5.0+1
  barcode_scan: ^0.0.4
  vibrate: ^0.0.4
  sqflite: ^1.1.1
  shared_preferences: ^0.5.1+1
  rxdart: ^0.20.0

dev_dependencies:
  intl_translation: ^0.17.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
