name: qr_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  path_provider: 0.4.1
  barcode_scan: ^0.0.4
  vibrate: any

flutter:

  uses-material-design: true
